// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kadntwscaxvzdbhinixd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZG50d3NjYXh2emRiaGluaXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Mjk3NjcsImV4cCI6MjA2MzIwNTc2N30.hdXGtJfdB20xyi_x9Or7xLTaORR2WgJ4Rywh540bcc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);